#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

// #define Trace(t)        printf("----------------------[trace]%s", t)
#define Trace(t)        printf("")
#define DEBUG 1 // change this to 1 to enable debug()
#define YY_parse_DEBUG 1
int yydebug = 1;

void bp() {
    printf("bp: %d\n", __LINE__);
}

void parser_debug(const char *msg) {
    if (DEBUG) {
        printf("-------[DEBUG]: %s\n", msg);
    }
}


enum type {
    _str,
    _int,
    _bool,
    _real,
    _char,
    _array,
    _function,
    _procedure,
    _int_array,
    _bool_array,
    _real_array
};

int currentScope = 0;
int subLoopEndCount=0;
int usedScopeCount = 0;
int subLoopStartCount = 0;
int union_type_temp_record = _int;

union Array{
    int* intArray;
    float* realArray;
}typedef Array;

struct unionData {
    int _const;
    int type;
    char strVal[256];
    int intVal;
    int boolVal;
    float realVal;
    Array array;
    int arrSize;
}typedef unionData;



typedef union {
    unionData data;
    int type;
    char idVal[256];
    int intVal;
    int boolVal;
    float realVal;
    char strVal[256];
}ret_union;


struct symbol {
    char id[256];
    enum type symbolType;
    ret_union unionVal;
    int scope;
    struct symbol *next;
}typedef symbol;

symbol *head = 0;


ret_union* lookup(char *id) {
    symbol *temp = head;
    while (temp != 0) {
        if (strcmp(temp->id, id) == 0) {
            return &(temp->unionVal);
        }
        temp = temp->next;
    }
    return 0;
}





void copyUnion(ret_union *lhs, ret_union *rhs) {
    if (lhs == 0 || rhs == 0) {
        return;
    }
    lhs->data._const = rhs->data._const;
    lhs->data.type = rhs->data.type;
    strcpy(lhs->data.strVal, rhs->data.strVal);
    lhs->data.intVal = rhs->data.intVal;
    lhs->data.boolVal = rhs->data.boolVal;
    lhs->data.realVal = rhs->data.realVal;
    lhs->data.arrSize = rhs->data.arrSize;

    if (rhs->data.type == _int_array|rhs->data.type == _bool_array)
    {
        lhs->data.array.intArray = (int*)malloc(sizeof(int) * rhs->data.arrSize);
        for(int i = 0; i < rhs->data.arrSize; i++)
        {
            lhs->data.array.intArray[i] = rhs->data.array.intArray[i];
        }
    }
    else if(rhs->data.type == _real_array)
    {
        lhs->data.array.realArray = (float*)malloc(sizeof(float) * rhs->data.arrSize);
        for(int i = 0; i < rhs->data.arrSize; i++)
        {
            lhs->data.array.realArray[i] = rhs->data.array.realArray[i];
        }
        
    }

}

symbol* create_symbol_entry() {
    
    symbol *new_entry = (symbol*)malloc(sizeof(symbol));
    new_entry->next = 0;
    new_entry->scope = 0;
    new_entry->symbolType = -1;

    return new_entry;
}






int insert_symbol(char *id, unionData *data) {
    symbol *temp = head;
    while (1) {
        if (strcmp(temp->id, id) == 0 && temp->scope == currentScope) {
            // already exists
            printf("variable repeat\n");
            yyerror("variable repeat");
            return 0;
        }
        if (temp->next == 0) {
            break;
        }
        temp = temp->next;
    }
    // not exists
    symbol *new_entry = (symbol*)malloc(sizeof(symbol));
    strcpy(new_entry->id, id);
    copyUnion(&(new_entry->unionVal), data);
    new_entry->symbolType = data->type;
    // print the union
    temp->next = new_entry;
    new_entry->next = 0;
    new_entry->scope = currentScope;
    return 1;
}



// dump
void dump_symbol() {
    symbol *temp = head;
    printf("\n\n\n\ndumping symbol table\n");
    while (temp != 0) {
        if(temp->symbolType != -1)
        {
            printf("id: [%s], scope: [%d]\n", temp->id, temp->scope);
            printUnion(&(temp->unionVal));
        }
        temp = temp->next;
    }
}




void printUnion(ret_union *ret) {
    printf("+++++++++++++++++++++++++++++++++++++++++\n");
    switch(ret->data.type) {
        case _function:
            printf("type %s\n", "function");
            break;
        case _procedure:
            printf("type %s\n", "_procedure");
            break;
        case _str:
            printf("type %s %s\n", ret->data._const?"const":"var", "string");
            printf("value: %s\n", ret->data.strVal);
            break;
        case _int:
            printf("type %s %s\n", ret->data._const?"const":"var", "int");
            printf("value: %d\n", ret->data.intVal);
            break;
        case _real:
            printf("type %s %s\n", ret->data._const?"const":"var", "real");
            printf("value: %f\n", ret->data.realVal);
            break;
        case _bool:
            printf("type %s %s\n", ret->data._const?"const":"var", "bool");
            printf("value: %d\n", ret->data.boolVal);
            break;
        case _int_array:
            printf("type %s %s\n", ret->data._const?"const":"var", "int array");
            printf("value: [");
            for(int i = 0; i < ret->data.arrSize; i++)
            {
                printf("%d ", ret->data.array.intArray[i]);
            }
            printf("]\n");
            break;
        case _real_array:
            printf("type %s %s\n", ret->data._const?"const":"var", "real array");
            printf("value: ");
            for(int i = 0; i < ret->data.arrSize; i++)
            {
                printf("%f ", ret->data.array.realArray[i]);
            }
            printf("\n");
            break;
        case _bool_array:
            printf("type %s %s\n", ret->data._const?"const":"var", "bool array");
            printf("value: ");
            for(int i = 0; i < ret->data.arrSize; i++)
            {
                printf("%d ", ret->data.array.intArray[i]);
            }
            printf("\n");
            break;

    }
    printf("+++++++++++++++++++++++++++++++++++++++++\n\n");

}



#line 251 "parser.y"
typedef union{
    struct _stuct {
        int _conts;
        int type;
        char strVal[256];
        int intVal;
        int boolVal;
        float realVal;
        int* arrayElements;
        int arrSize;
    }data;

    int type;
    char idVal[256];
    int intVal;
    int boolVal;
    float realVal;
    char strVal[256];
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	STRING	258
#define	BOOL	259
#define	CHAR	260
#define	FLOAT	261
#define	INT	262
#define	ARRAY	263
#define	REAL	264
#define	STRING_VALUE	265
#define	REAL_VALUE	266
#define	INTEGER_VALUE	267
#define	TRUE_VALUE	268
#define	FALSE_VALUE	269
#define	IDENTIFIER	270
#define	COLON	271
#define	COMMA	272
#define	DOT	273
#define	OF	274
#define	END	275
#define	IF	276
#define	THEN	277
#define	ELSE	278
#define	LOOP	279
#define	FOR	280
#define	DECREASING	281
#define	bg	282
#define	LPAREN	283
#define	RPAREN	284
#define	LBRACKET	285
#define	RBRACKET	286
#define	LBRACE	287
#define	RBRACE	288
#define	FUNCTION	289
#define	PROCEDURE	290
#define	LESS	291
#define	GREATER	292
#define	WHEN	293
#define	SKIP	294
#define	EXIT	295
#define	RESULT	296
#define	RETURN	297
#define	PUT	298
#define	GET	299
#define	AND	300
#define	OR	301
#define	NOT	302
#define	GREATER_EQUAL	303
#define	LESS_EQUAL	304
#define	EQUAL	305
#define	NOT_EQUAL	306
#define	ASSIGN	307
#define	VAR	308
#define	CONST	309
#define	SEMICOLON	310
#define	PLUS	311
#define	MINUS	312
#define	TIMES	313
#define	DIVIDE	314
#define	MOD	315
#define	UMINUS	316


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int STRING;
static const int BOOL;
static const int CHAR;
static const int FLOAT;
static const int INT;
static const int ARRAY;
static const int REAL;
static const int STRING_VALUE;
static const int REAL_VALUE;
static const int INTEGER_VALUE;
static const int TRUE_VALUE;
static const int FALSE_VALUE;
static const int IDENTIFIER;
static const int COLON;
static const int COMMA;
static const int DOT;
static const int OF;
static const int END;
static const int IF;
static const int THEN;
static const int ELSE;
static const int LOOP;
static const int FOR;
static const int DECREASING;
static const int bg;
static const int LPAREN;
static const int RPAREN;
static const int LBRACKET;
static const int RBRACKET;
static const int LBRACE;
static const int RBRACE;
static const int FUNCTION;
static const int PROCEDURE;
static const int LESS;
static const int GREATER;
static const int WHEN;
static const int SKIP;
static const int EXIT;
static const int RESULT;
static const int RETURN;
static const int PUT;
static const int GET;
static const int AND;
static const int OR;
static const int NOT;
static const int GREATER_EQUAL;
static const int LESS_EQUAL;
static const int EQUAL;
static const int NOT_EQUAL;
static const int ASSIGN;
static const int VAR;
static const int CONST;
static const int SEMICOLON;
static const int PLUS;
static const int MINUS;
static const int TIMES;
static const int DIVIDE;
static const int MOD;
static const int UMINUS;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,STRING=258
	,BOOL=259
	,CHAR=260
	,FLOAT=261
	,INT=262
	,ARRAY=263
	,REAL=264
	,STRING_VALUE=265
	,REAL_VALUE=266
	,INTEGER_VALUE=267
	,TRUE_VALUE=268
	,FALSE_VALUE=269
	,IDENTIFIER=270
	,COLON=271
	,COMMA=272
	,DOT=273
	,OF=274
	,END=275
	,IF=276
	,THEN=277
	,ELSE=278
	,LOOP=279
	,FOR=280
	,DECREASING=281
	,bg=282
	,LPAREN=283
	,RPAREN=284
	,LBRACKET=285
	,RBRACKET=286
	,LBRACE=287
	,RBRACE=288
	,FUNCTION=289
	,PROCEDURE=290
	,LESS=291
	,GREATER=292
	,WHEN=293
	,SKIP=294
	,EXIT=295
	,RESULT=296
	,RETURN=297
	,PUT=298
	,GET=299
	,AND=300
	,OR=301
	,NOT=302
	,GREATER_EQUAL=303
	,LESS_EQUAL=304
	,EQUAL=305
	,NOT_EQUAL=306
	,ASSIGN=307
	,VAR=308
	,CONST=309
	,SEMICOLON=310
	,PLUS=311
	,MINUS=312
	,TIMES=313
	,DIVIDE=314
	,MOD=315
	,UMINUS=316


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::STRING=258;
const int YY_parse_CLASS::BOOL=259;
const int YY_parse_CLASS::CHAR=260;
const int YY_parse_CLASS::FLOAT=261;
const int YY_parse_CLASS::INT=262;
const int YY_parse_CLASS::ARRAY=263;
const int YY_parse_CLASS::REAL=264;
const int YY_parse_CLASS::STRING_VALUE=265;
const int YY_parse_CLASS::REAL_VALUE=266;
const int YY_parse_CLASS::INTEGER_VALUE=267;
const int YY_parse_CLASS::TRUE_VALUE=268;
const int YY_parse_CLASS::FALSE_VALUE=269;
const int YY_parse_CLASS::IDENTIFIER=270;
const int YY_parse_CLASS::COLON=271;
const int YY_parse_CLASS::COMMA=272;
const int YY_parse_CLASS::DOT=273;
const int YY_parse_CLASS::OF=274;
const int YY_parse_CLASS::END=275;
const int YY_parse_CLASS::IF=276;
const int YY_parse_CLASS::THEN=277;
const int YY_parse_CLASS::ELSE=278;
const int YY_parse_CLASS::LOOP=279;
const int YY_parse_CLASS::FOR=280;
const int YY_parse_CLASS::DECREASING=281;
const int YY_parse_CLASS::bg=282;
const int YY_parse_CLASS::LPAREN=283;
const int YY_parse_CLASS::RPAREN=284;
const int YY_parse_CLASS::LBRACKET=285;
const int YY_parse_CLASS::RBRACKET=286;
const int YY_parse_CLASS::LBRACE=287;
const int YY_parse_CLASS::RBRACE=288;
const int YY_parse_CLASS::FUNCTION=289;
const int YY_parse_CLASS::PROCEDURE=290;
const int YY_parse_CLASS::LESS=291;
const int YY_parse_CLASS::GREATER=292;
const int YY_parse_CLASS::WHEN=293;
const int YY_parse_CLASS::SKIP=294;
const int YY_parse_CLASS::EXIT=295;
const int YY_parse_CLASS::RESULT=296;
const int YY_parse_CLASS::RETURN=297;
const int YY_parse_CLASS::PUT=298;
const int YY_parse_CLASS::GET=299;
const int YY_parse_CLASS::AND=300;
const int YY_parse_CLASS::OR=301;
const int YY_parse_CLASS::NOT=302;
const int YY_parse_CLASS::GREATER_EQUAL=303;
const int YY_parse_CLASS::LESS_EQUAL=304;
const int YY_parse_CLASS::EQUAL=305;
const int YY_parse_CLASS::NOT_EQUAL=306;
const int YY_parse_CLASS::ASSIGN=307;
const int YY_parse_CLASS::VAR=308;
const int YY_parse_CLASS::CONST=309;
const int YY_parse_CLASS::SEMICOLON=310;
const int YY_parse_CLASS::PLUS=311;
const int YY_parse_CLASS::MINUS=312;
const int YY_parse_CLASS::TIMES=313;
const int YY_parse_CLASS::DIVIDE=314;
const int YY_parse_CLASS::MOD=315;
const int YY_parse_CLASS::UMINUS=316;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		214
#define	YYFLAG		-32768
#define	YYNTBASE	62

#define YYTRANSLATE(x) ((unsigned)(x) <= 316 ? yytranslate[x] : 101)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     7,     9,    11,    13,    15,    17,    19,
    22,    27,    30,    32,    34,    36,    38,    41,    43,    46,
    48,    56,    65,    69,    73,    75,    77,    79,    83,    85,
    88,    90,    92,    94,    96,    98,   100,   102,   105,   107,
   109,   111,   114,   116,   119,   121,   125,   129,   132,   135,
   138,   140,   142,   146,   148,   151,   160,   167,   169,   171,
   173,   175,   177,   179,   181,   183,   185,   187,   192,   197,
   199,   201,   205,   209,   213,   217,   221,   225,   229,   233,
   237,   241,   245,   249,   253,   257,   261,   263,   265,   269,
   272,   275,   277,   285,   288,   290,   300,   301,   305,   308,
   313,   314,   319,   326,   331,   338,   343,   354,   356,   358,
   360,   362
};

static const short yyrhs[] = {    63,
     0,    64,     0,    63,    64,     0,    66,     0,    84,     0,
    76,     0,    82,     0,    68,     0,    65,     0,     0,    65,
     0,    15,    28,    73,    29,     0,    66,    67,     0,    67,
     0,    99,     0,    93,     0,    90,     0,    68,    69,     0,
    69,     0,    70,    71,     0,    24,     0,    25,    15,    16,
    72,    18,    18,    72,     0,    25,    26,    15,    16,    72,
    18,    18,    72,     0,    74,    20,    24,     0,    74,    20,
    25,     0,    15,     0,    12,     0,    84,     0,    73,    17,
    84,     0,    98,     0,    74,    75,     0,    75,     0,    83,
     0,    69,     0,    66,     0,    76,     0,    98,     0,    77,
     0,    76,    77,     0,    78,     0,    81,     0,    65,     0,
    79,    80,     0,    27,     0,    74,    20,     0,    39,     0,
    15,    52,    84,     0,    86,    52,    84,     0,    44,    15,
     0,    43,    84,     0,    41,    84,     0,    42,     0,    40,
     0,    40,    38,    88,     0,    83,     0,    82,    83,     0,
    21,    88,    22,    74,    23,    74,    20,    21,     0,    21,
    88,    22,    74,    20,    21,     0,    89,     0,    88,     0,
    87,     0,    86,     0,    85,     0,    10,     0,    13,     0,
    14,     0,    12,     0,    11,     0,    15,    30,    12,    31,
     0,    15,    28,    73,    29,     0,    15,     0,    85,     0,
    28,    84,    29,     0,    84,    50,    84,     0,    84,    51,
    84,     0,    84,    37,    84,     0,    84,    36,    84,     0,
    84,    48,    84,     0,    84,    49,    84,     0,    84,    45,
    84,     0,    84,    46,    84,     0,    84,    47,    84,     0,
    89,    58,    89,     0,    89,    59,    89,     0,    89,    57,
    89,     0,    89,    56,    89,     0,    89,    60,    89,     0,
    15,     0,    85,     0,    28,    89,    29,     0,    57,    89,
     0,    91,    92,     0,    35,     0,    15,    28,    96,    29,
    74,    20,    15,     0,    94,    95,     0,    34,     0,    15,
    28,    96,    29,    16,   100,    74,    20,    15,     0,     0,
    15,    16,   100,     0,    96,    97,     0,    17,    15,    16,
   100,     0,     0,    54,    15,    52,    84,     0,    54,    15,
    16,   100,    52,    84,     0,    53,    15,    16,   100,     0,
    53,    15,    16,   100,    52,    84,     0,    53,    15,    52,
    84,     0,    53,    15,    16,     8,    72,    18,    18,    72,
    19,   100,     0,     3,     0,     4,     0,     5,     0,     9,
     0,     7,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   304,   309,   312,   315,   320,   324,   328,   332,   342,   347,
   352,   359,   363,   367,   372,   376,   382,   386,   391,   397,
   401,   404,   409,   413,   418,   431,   437,   443,   448,   456,
   461,   466,   471,   475,   479,   484,   491,   496,   504,   509,
   514,   520,   526,   538,   554,   559,   571,   576,   581,   585,
   589,   594,   599,   609,   613,   618,   624,   632,   640,   645,
   650,   655,   694,   704,   710,   716,   723,   731,   741,   747,
   754,   760,   766,   772,   778,   784,   790,   796,   802,   808,
   814,   826,   852,   878,   905,   931,   942,   963,   977,   992,
  1015,  1021,  1039,  1065,  1071,  1089,  1114,  1115,  1124,  1129,
  1140,  1146,  1155,  1167,  1177,  1189,  1197,  1236,  1241,  1245,
  1249,  1253
};

static const char * const yytname[] = {   "$","error","$illegal.","STRING","BOOL",
"CHAR","FLOAT","INT","ARRAY","REAL","STRING_VALUE","REAL_VALUE","INTEGER_VALUE",
"TRUE_VALUE","FALSE_VALUE","IDENTIFIER","COLON","COMMA","DOT","OF","END","IF",
"THEN","ELSE","LOOP","FOR","DECREASING","bg","LPAREN","RPAREN","LBRACKET","RBRACKET",
"LBRACE","RBRACE","FUNCTION","PROCEDURE","LESS","GREATER","WHEN","SKIP","EXIT",
"RESULT","RETURN","PUT","GET","AND","OR","NOT","GREATER_EQUAL","LESS_EQUAL",
"EQUAL","NOT_EQUAL","ASSIGN","VAR","CONST","SEMICOLON","PLUS","MINUS","TIMES",
"DIVIDE","MOD","UMINUS","program","multiple_subprogram","subprogram","procedure_invocation",
"multi_declaration","declaration","loops","loop","loopStart","loopEnd","integer_id",
"args","function_contents","function_content","multi_statements","statement",
"blocks","blockStart","blockEnd","simple","conditions","condition","expression",
"variable_value","array_reference","function_invocation","bool_expression","arithmetic_expression",
"procedure_declaration","procedureStart","procedureEND","function_declaration",
"functionStart","functionEND","args_declaration","more_args_declaration","empty",
"variable_declaration","variable_type","variable_type"
};
#endif

static const short yyr1[] = {     0,
    62,    63,    63,    64,    64,    64,    64,    64,    -1,    -1,
    65,    66,    66,    67,    67,    67,    68,    68,    69,    70,
    70,    70,    71,    71,    72,    72,    73,    73,    73,    74,
    74,    75,    75,    75,    75,    75,    76,    76,    77,    77,
    77,    78,    79,    80,    81,    81,    81,    81,    81,    81,
    81,    81,    81,    82,    82,    83,    83,    84,    84,    84,
    84,    84,    85,    85,    85,    85,    85,    86,    87,    88,
    88,    88,    88,    88,    88,    88,    88,    88,    88,    88,
    88,    89,    89,    89,    89,    89,    89,    89,    89,    89,
    90,    91,    92,    93,    94,    95,    96,    96,    96,    97,
    98,    99,    99,    99,    99,    99,    99,   100,   100,   100,
   100,   100
};

static const short yyr2[] = {     0,
     1,     1,     2,     1,     1,     1,     1,     1,     1,     2,
     4,     2,     1,     1,     1,     1,     2,     1,     2,     1,
     7,     8,     3,     3,     1,     1,     1,     3,     1,     2,
     1,     1,     1,     1,     1,     1,     1,     2,     1,     1,
     1,     2,     1,     2,     1,     3,     3,     2,     2,     2,
     1,     1,     3,     1,     2,     8,     6,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     4,     4,     1,
     1,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     1,     1,     3,     2,
     2,     1,     7,     2,     1,     9,     0,     3,     2,     4,
     0,     4,     6,     4,     6,     4,    10,     1,     1,     1,
     1,     1
};

static const short yydefact[] = {     0,
    63,    67,    66,    64,    65,    70,     0,    20,     0,    43,
     0,    95,    92,    45,    52,     0,    51,     0,     0,     0,
     0,     0,     1,     2,    41,     4,    13,     8,    18,   101,
     6,    37,    39,   101,    40,     7,    54,     5,    62,    61,
    60,    59,    58,    16,     0,    15,     0,    14,   101,     0,
     0,    70,     0,    61,    59,     0,     0,     0,    58,     0,
    50,    49,    48,     0,     0,    87,     0,    88,    90,     3,
    12,    17,     0,    34,    33,    19,     0,    31,    35,    32,
     0,    36,    38,     0,    42,    55,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    91,     0,    94,     0,    27,    29,     0,    46,
   101,   101,     0,     0,    72,    89,    53,     0,     0,     0,
     0,     0,   101,     0,    30,    44,    76,    75,    79,    80,
    81,    77,    78,    73,    74,    47,    85,    84,    82,    83,
    86,    97,    97,     0,    11,    68,     0,     0,    26,    25,
     0,     0,   108,   109,   110,   112,     0,   111,   104,   106,
     0,   102,     0,    23,    24,     0,     0,     0,    28,    69,
     0,   101,     0,     0,     0,     0,     0,    11,     0,     0,
   101,    99,     0,    57,     0,     0,     0,     0,   105,   103,
    98,     0,     0,     0,     0,    21,     0,     0,     0,     0,
   101,    56,    22,     0,   100,    93,     0,     0,     0,   107,
    96,     0,     0,     0
};

static const short yydefgoto[] = {   212,
    23,    24,    25,    74,    27,    28,    75,    30,    76,   151,
   106,    77,    78,    79,    32,    33,    34,    85,    35,    36,
    80,   107,    39,    54,    41,    42,    43,    44,    45,   103,
    46,    47,   105,   167,   182,    82,    48,   159
};

static const short yypact[] = {   184,
-32768,-32768,-32768,-32768,-32768,   408,   143,-32768,     7,-32768,
   143,-32768,-32768,-32768,     2,   143,-32768,   143,    28,    31,
    57,   176,   184,-32768,-32768,    -6,-32768,    43,-32768,   405,
   435,-32768,-32768,   405,-32768,    44,-32768,   436,   124,    34,
-32768,-32768,    50,-32768,    72,-32768,    84,-32768,   143,   105,
   143,   104,   436,-32768,    99,   107,   116,   406,   191,   143,
   436,   436,-32768,    -1,    10,-32768,   176,-32768,-32768,-32768,
-32768,-32768,   -10,    -6,-32768,-32768,   250,-32768,   435,-32768,
    34,-32768,-32768,   281,-32768,-32768,   143,   143,   143,   143,
   143,   143,   143,   143,   143,   143,   176,   176,   176,   176,
   176,   113,-32768,   114,-32768,    24,   436,-32768,   112,   436,
   143,   405,    23,   128,-32768,-32768,   452,   121,   143,   508,
   143,   191,   143,    58,-32768,-32768,   436,   436,   436,   436,
   436,   436,   436,   436,   436,   436,    56,    56,-32768,-32768,
-32768,   131,   131,   143,   459,-32768,    42,   219,-32768,-32768,
   129,    23,-32768,-32768,-32768,-32768,    23,-32768,    98,   436,
   100,   436,    46,-32768,-32768,   135,    47,    52,   436,-32768,
   138,   405,   147,   148,   149,   143,   143,-32768,   508,   146,
   405,-32768,   152,-32768,   312,    23,   155,   156,   436,   436,
-32768,   154,   343,   508,   158,-32768,    23,    23,   508,   160,
   405,-32768,-32768,   157,-32768,-32768,   374,   508,   177,-32768,
-32768,   202,   203,-32768
};

static const short yypgoto[] = {-32768,
-32768,   183,-32768,    21,   -20,-32768,     9,-32768,-32768,  -141,
   -38,   -32,   -74,    27,   -24,-32768,-32768,-32768,-32768,-32768,
    13,     1,    38,     0,-32768,    -2,     3,-32768,-32768,-32768,
-32768,-32768,-32768,    67,-32768,   -45,-32768,   -81
};


#define	YYLAST		517


static const short yytable[] = {    40,
    38,    84,   125,   108,    55,    71,    83,    53,    29,   125,
   174,    58,    37,    59,   118,   175,    61,   123,    62,    50,
    26,    56,    40,    38,    69,   120,    31,    12,    13,    81,
    81,    29,    57,    81,   149,    37,    72,   150,   161,    60,
   144,    51,    63,    26,   196,    64,    20,    21,    86,    31,
   119,   110,   145,    71,    83,   203,   204,   117,   144,    68,
    53,   121,   144,   180,     7,   108,     8,     9,   180,   122,
   170,    65,   147,   125,   178,   181,    81,   108,    81,   148,
   183,   164,   165,    81,   163,    96,   102,   127,   128,   129,
   130,   131,   132,   133,   134,   135,   136,   191,   104,   137,
   138,   139,   140,   141,    68,    97,    98,    99,   100,   101,
   125,    81,   201,    99,   100,   101,   109,   205,   125,   160,
   112,   162,   113,   153,   154,   155,   210,   156,   157,   158,
   114,   111,   125,    50,    68,    68,    68,    68,    68,   185,
   142,   143,   146,   152,   169,   166,   173,    81,   193,   176,
   179,   177,     1,     2,     3,     4,     5,    52,   184,   -87,
   192,   -87,   -87,   -87,   186,   187,   188,   194,   207,   199,
    11,    81,   197,   198,   206,   208,   189,   190,   202,   -88,
    81,   -88,   -88,   -88,    81,     1,     2,     3,     4,     5,
    66,   211,    81,     1,     2,     3,     4,     5,     6,    22,
    81,   213,   214,    67,     7,    70,    81,     8,     9,   168,
    10,    11,     0,     0,     0,     0,     0,    12,    13,   116,
     0,     0,    14,    15,    16,    17,    18,    19,     0,     0,
     0,     0,    22,    73,     0,     0,    20,    21,   171,     7,
    22,   172,     8,     9,     0,    10,    97,    98,    99,   100,
   101,     0,    12,    13,     0,     0,     0,    14,    15,    16,
    17,    18,    19,     0,    73,     0,     0,     0,     0,   124,
     7,    20,    21,     8,     9,     0,    10,     0,     0,     0,
     0,     0,     0,    12,    13,     0,     0,     0,    14,    15,
    16,    17,    18,    19,     0,    73,     0,     0,     0,     0,
   126,     7,    20,    21,     8,     9,     0,    10,     0,     0,
     0,     0,     0,     0,    12,    13,     0,     0,     0,    14,
    15,    16,    17,    18,    19,     0,    73,     0,     0,     0,
     0,   195,     7,    20,    21,     8,     9,     0,    10,     0,
     0,     0,     0,     0,     0,    12,    13,     0,     0,     0,
    14,    15,    16,    17,    18,    19,     0,    73,     0,     0,
     0,     0,   200,     7,    20,    21,     8,     9,     0,    10,
     0,     0,     0,     0,     0,     0,    12,    13,     0,     0,
     0,    14,    15,    16,    17,    18,    19,     0,    73,     0,
     0,     0,     0,   209,     7,    20,    21,     8,     9,     0,
    10,     0,     0,     0,     0,     0,     0,    12,    13,     0,
     0,     0,    14,    15,    16,    17,    18,    19,     0,    73,
     0,     0,     0,     0,     0,     7,    20,    21,     8,     9,
     0,    10,     0,     0,   115,    49,     0,    50,    12,    13,
     0,    87,    88,    14,    15,    16,    17,    18,    19,    73,
    89,    90,    91,    92,    93,    94,    95,    20,    21,    51,
     0,    10,     0,   -87,     0,   -87,   -87,   -87,     0,     0,
     0,    87,    88,    14,    15,    16,    17,    18,    19,     0,
    89,    90,    91,    92,    93,    94,    95,   -59,   -59,     0,
     0,     0,     0,     0,   -69,   -69,   -59,   -59,   -59,   -59,
   -59,   -59,   -59,   -69,   -69,   -69,   -69,   -69,   -69,   -69,
   153,   154,   155,     0,   156,     0,   158
};

static const short yycheck[] = {     0,
     0,    34,    77,    49,     7,    26,    31,     7,     0,    84,
   152,    11,     0,    11,    16,   157,    16,    28,    18,    30,
     0,    15,    23,    23,    22,    16,     0,    34,    35,    30,
    31,    23,    26,    34,    12,    23,    28,    15,   120,    38,
    17,    52,    15,    23,   186,    15,    53,    54,    36,    23,
    52,    51,    29,    74,    79,   197,   198,    60,    17,    22,
    60,    52,    17,    17,    21,   111,    24,    25,    17,    67,
    29,    15,   111,   148,    29,    29,    77,   123,    79,   112,
    29,    24,    25,    84,   123,    52,    15,    87,    88,    89,
    90,    91,    92,    93,    94,    95,    96,   179,    15,    97,
    98,    99,   100,   101,    67,    56,    57,    58,    59,    60,
   185,   112,   194,    58,    59,    60,    12,   199,   193,   119,
    22,   121,    16,     3,     4,     5,   208,     7,     8,     9,
    15,    28,   207,    30,    97,    98,    99,   100,   101,   172,
    28,    28,    31,    16,   144,    15,    18,   148,   181,    52,
    16,    52,    10,    11,    12,    13,    14,    15,    21,    56,
    15,    58,    59,    60,    18,    18,    18,    16,   201,    16,
    28,   172,    18,    18,    15,    19,   176,   177,    21,    56,
   181,    58,    59,    60,   185,    10,    11,    12,    13,    14,
    15,    15,   193,    10,    11,    12,    13,    14,    15,    57,
   201,     0,     0,    28,    21,    23,   207,    24,    25,   143,
    27,    28,    -1,    -1,    -1,    -1,    -1,    34,    35,    29,
    -1,    -1,    39,    40,    41,    42,    43,    44,    -1,    -1,
    -1,    -1,    57,    15,    -1,    -1,    53,    54,    20,    21,
    57,    23,    24,    25,    -1,    27,    56,    57,    58,    59,
    60,    -1,    34,    35,    -1,    -1,    -1,    39,    40,    41,
    42,    43,    44,    -1,    15,    -1,    -1,    -1,    -1,    20,
    21,    53,    54,    24,    25,    -1,    27,    -1,    -1,    -1,
    -1,    -1,    -1,    34,    35,    -1,    -1,    -1,    39,    40,
    41,    42,    43,    44,    -1,    15,    -1,    -1,    -1,    -1,
    20,    21,    53,    54,    24,    25,    -1,    27,    -1,    -1,
    -1,    -1,    -1,    -1,    34,    35,    -1,    -1,    -1,    39,
    40,    41,    42,    43,    44,    -1,    15,    -1,    -1,    -1,
    -1,    20,    21,    53,    54,    24,    25,    -1,    27,    -1,
    -1,    -1,    -1,    -1,    -1,    34,    35,    -1,    -1,    -1,
    39,    40,    41,    42,    43,    44,    -1,    15,    -1,    -1,
    -1,    -1,    20,    21,    53,    54,    24,    25,    -1,    27,
    -1,    -1,    -1,    -1,    -1,    -1,    34,    35,    -1,    -1,
    -1,    39,    40,    41,    42,    43,    44,    -1,    15,    -1,
    -1,    -1,    -1,    20,    21,    53,    54,    24,    25,    -1,
    27,    -1,    -1,    -1,    -1,    -1,    -1,    34,    35,    -1,
    -1,    -1,    39,    40,    41,    42,    43,    44,    -1,    15,
    -1,    -1,    -1,    -1,    -1,    21,    53,    54,    24,    25,
    -1,    27,    -1,    -1,    29,    28,    -1,    30,    34,    35,
    -1,    36,    37,    39,    40,    41,    42,    43,    44,    15,
    45,    46,    47,    48,    49,    50,    51,    53,    54,    52,
    -1,    27,    -1,    56,    -1,    58,    59,    60,    -1,    -1,
    -1,    36,    37,    39,    40,    41,    42,    43,    44,    -1,
    45,    46,    47,    48,    49,    50,    51,    36,    37,    -1,
    -1,    -1,    -1,    -1,    36,    37,    45,    46,    47,    48,
    49,    50,    51,    45,    46,    47,    48,    49,    50,    51,
     3,     4,     5,    -1,     7,    -1,     9
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 305 "parser.y"
{
    Trace("Reducing to program\n");
;
    break;}
case 2:
#line 311 "parser.y"
{;
    break;}
case 3:
#line 313 "parser.y"
{;
    break;}
case 4:
#line 317 "parser.y"
{
    Trace("Reducing to subprogram\n");
;
    break;}
case 5:
#line 321 "parser.y"
{
    Trace("Reducing to subprogram\n");
;
    break;}
case 6:
#line 325 "parser.y"
{
    Trace("Reducing to subprogram\n");
;
    break;}
case 7:
#line 329 "parser.y"
{
    Trace("Reducing to subprogram\n");
;
    break;}
case 8:
#line 333 "parser.y"
{
    Trace("Reducing to subprogram\n");
;
    break;}
case 9:
#line 344 "parser.y"
{
    Trace("Reducing to procedure_invocations\n");
;
    break;}
case 10:
#line 348 "parser.y"
{
    Trace("Reducing to procedure_invocations\n");
;
    break;}
case 11:
#line 354 "parser.y"
{
    Trace("Reducing to procedure_invocation\n");
;
    break;}
case 12:
#line 361 "parser.y"
{
;
    break;}
case 13:
#line 364 "parser.y"
{
;
    break;}
case 14:
#line 369 "parser.y"
{
    Trace("Reducing to variable declaration\n");
;
    break;}
case 15:
#line 373 "parser.y"
{
    Trace("Reducing to function_declaration\n");
;
    break;}
case 16:
#line 377 "parser.y"
{
    Trace("Reducing to procedure_declaration\n");
;
    break;}
case 17:
#line 384 "parser.y"
{
;
    break;}
case 18:
#line 387 "parser.y"
{
;
    break;}
case 19:
#line 393 "parser.y"
{
    Trace("Reducing to loop\n");
;
    break;}
case 20:
#line 399 "parser.y"
{
;
    break;}
case 21:
#line 402 "parser.y"
{
;
    break;}
case 22:
#line 405 "parser.y"
{
;
    break;}
case 23:
#line 411 "parser.y"
{
;
    break;}
case 24:
#line 414 "parser.y"
{
;
    break;}
case 25:
#line 420 "parser.y"
{
    ret_union* data = lookup(yyvsp[0].idVal);
    if(!data)
    {
        printf("Error: %s is not declared\n", yyvsp[0].idVal);
        exit(1);
    }
    yyval.intVal = data->data.intVal;
    Trace("Reducing to integer_id\n");
    
;
    break;}
case 26:
#line 432 "parser.y"
{
    Trace("Reducing to integer_id\n");
;
    break;}
case 27:
#line 439 "parser.y"
{
    Trace("Reducing to args\n");
    
;
    break;}
case 28:
#line 444 "parser.y"
{
    Trace("Reducing to args\n");
    
;
    break;}
case 29:
#line 449 "parser.y"
{
    Trace("Reducing to args\n");
;
    break;}
case 30:
#line 458 "parser.y"
{
    Trace("Reducing to function_contents\n");
;
    break;}
case 31:
#line 462 "parser.y"
{
    Trace("Reducing to function_contents\n");
;
    break;}
case 32:
#line 468 "parser.y"
{
    Trace("Reducing to function_contents\n");
;
    break;}
case 33:
#line 472 "parser.y"
{
    Trace("Reducing to function_contents\n");
;
    break;}
case 34:
#line 476 "parser.y"
{
    Trace("Reducing to function_contents\n");
;
    break;}
case 35:
#line 480 "parser.y"
{
    Trace("Reducing to function_contents\n");

;
    break;}
case 36:
#line 485 "parser.y"
{
    Trace("Reducing to function_contents\n");

;
    break;}
case 37:
#line 493 "parser.y"
{
    Trace("Reducing to multi_statements\n");
;
    break;}
case 38:
#line 497 "parser.y"
{
    Trace("Reducing to multi_statements\n");

;
    break;}
case 39:
#line 506 "parser.y"
{
    Trace("Reducing to statement\n");
;
    break;}
case 40:
#line 510 "parser.y"
{
    Trace("Reducing to statement\n");
    
;
    break;}
case 41:
#line 515 "parser.y"
{
    Trace("Reducing to statement\n");
    
;
    break;}
case 42:
#line 522 "parser.y"
{
    Trace("Reducing to blocks\n");
;
    break;}
case 43:
#line 528 "parser.y"
{
    currentScope = currentScope + usedScopeCount + 1;
    if(subLoopStartCount != 0)
    {
        currentScope = currentScope - usedScopeCount;
    }
    subLoopStartCount++;
    usedScopeCount++;
;
    break;}
case 44:
#line 540 "parser.y"
{
    currentScope--;
    subLoopEndCount++;
    if(subLoopStartCount == subLoopEndCount)
    {
        currentScope = currentScope - usedScopeCount + subLoopEndCount;
        subLoopEndCount = 0;
        subLoopStartCount = 0;
    }
;
    break;}
case 45:
#line 556 "parser.y"
{
    Trace("Reducing to simple\n");
;
    break;}
case 46:
#line 560 "parser.y"
{

    ret_union* data = lookup(yyvsp[-2].idVal);
    if(!data)
    {
        printf("Error: %s is not declared\n", yyvsp[-2].idVal);
        exit(1);
    }
    copyUnion(data, (ret_union*)&yyvsp[0].data);
    Trace("Reducing to simple\n");
;
    break;}
case 47:
#line 572 "parser.y"
{

    Trace("Reducing to simple\n");
;
    break;}
case 48:
#line 577 "parser.y"
{
    bp();
    Trace("Reducing to simple\n");
;
    break;}
case 49:
#line 582 "parser.y"
{
    Trace("Reducing to simple\n");
;
    break;}
case 50:
#line 586 "parser.y"
{
    Trace("Reducing to simple\n");
;
    break;}
case 51:
#line 590 "parser.y"
{
    Trace("Reducing to simple\n");

;
    break;}
case 52:
#line 595 "parser.y"
{
    Trace("Reducing to simple\n");

;
    break;}
case 53:
#line 600 "parser.y"
{
    Trace("Reducing to simple\n");

;
    break;}
case 54:
#line 611 "parser.y"
{
;
    break;}
case 55:
#line 614 "parser.y"
{
;
    break;}
case 56:
#line 620 "parser.y"
{
    
    Trace("Reducing to condition\n");
;
    break;}
case 57:
#line 625 "parser.y"
{
    
    Trace("Reducing to condition\n");
;
    break;}
case 58:
#line 634 "parser.y"
{
    // print $1
    Trace("Reducing to expression\n");
    copyUnion((ret_union*)&yyval.data, (ret_union*)&yyvsp[0].data);
    
;
    break;}
case 59:
#line 641 "parser.y"
{
    Trace("Reducing to expression\n");
    
;
    break;}
case 60:
#line 646 "parser.y"
{
    Trace("Reducing to expression\n");
    
;
    break;}
case 61:
#line 651 "parser.y"
{
    Trace("Reducing to expression\n");
    
;
    break;}
case 62:
#line 656 "parser.y"
{
    Trace("Reducing to expression\n");
    switch(yyvsp[0].data.type)
    {
        case _int:
        {
            yyval.data.intVal = yyvsp[0].data.intVal;
            yyval.data.type = _int;
            break;
        }
        case _real:
        {
            yyval.data.intVal = yyvsp[0].data.realVal;
            yyval.data.type = _real;
            break;
        }
        case _bool:
        {
            yyval.data.intVal = yyvsp[0].data.boolVal;
            yyval.data.type = _bool;
            break;
        }
        case _str:
        {
            strcpy(yyval.data.strVal, yyvsp[0].data.strVal);
            yyval.data.type = _str;
            break;
        }
        default:
        {
            break;
        }
    }
    
;
    break;}
case 63:
#line 696 "parser.y"
{
    char test[100];
    strcpy(test, yyvsp[0].strVal);
    Trace("Reducing to variable_value\n");
    strcpy(yyval.data.strVal, yyvsp[0].strVal);
    yyval.data.type = _str;

;
    break;}
case 64:
#line 705 "parser.y"
{
    Trace("Reducing to variable_value\n");
    yyval.data.boolVal = 1;
    yyval.data.type = _bool;
;
    break;}
case 65:
#line 711 "parser.y"
{
    Trace("Reducing to variable_value\n");
    yyval.data.boolVal = 0;
    yyval.data.type = _bool;
;
    break;}
case 66:
#line 717 "parser.y"
{
    
    Trace("Reducing to variable_value\n");
    yyval.data.intVal = yyvsp[0].intVal;
    yyval.data.type = _int;
;
    break;}
case 67:
#line 724 "parser.y"
{
    Trace("Reducing to variable_value\n");
    yyval.data.realVal = yyvsp[0].realVal;
    yyval.data.type = _real;
;
    break;}
case 68:
#line 733 "parser.y"
{
    Trace("Reducing to array_reference\n");
;
    break;}
case 69:
#line 743 "parser.y"
{
    Trace("Reducing to function_invocation\n");
;
    break;}
case 70:
#line 749 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");
    
;
    break;}
case 71:
#line 755 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 72:
#line 761 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 73:
#line 767 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 74:
#line 773 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 75:
#line 779 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 76:
#line 785 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 77:
#line 791 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 78:
#line 797 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 79:
#line 803 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 80:
#line 809 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 81:
#line 815 "parser.y"
{
    yyval.data.type = _bool;
    Trace("Reducing to bool_expression\n");

;
    break;}
case 82:
#line 828 "parser.y"
{
    Trace("Reducing to arithmetic_expression\n");    
    if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _int)
    {
        yyval.data.intVal = yyvsp[-2].data.intVal * yyvsp[0].data.intVal;
        yyval.data.type = _int;
    }
    else if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.intVal * yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _int)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal * yyvsp[0].data.intVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal * yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }

;
    break;}
case 83:
#line 853 "parser.y"
{
    
    Trace("Reducing to arithmetic_expression\n");    
    if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _int)
    {
        yyval.data.intVal = yyvsp[-2].data.intVal / yyvsp[0].data.intVal;
        yyval.data.type = _int;
    }
    else if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.intVal / yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _int)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal / yyvsp[0].data.intVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal / yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }

;
    break;}
case 84:
#line 879 "parser.y"
{
    

    Trace("Reducing to arithmetic_expression\n");    
    if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _int)
    {
        yyval.data.intVal = yyvsp[-2].data.intVal - yyvsp[0].data.intVal;
        yyval.data.type = _int;
    }
    else if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.intVal - yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _int)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal - yyvsp[0].data.intVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal - yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }

;
    break;}
case 85:
#line 906 "parser.y"
{
    Trace("Reducing to arithmetic_expression\n");    
    
    if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _int)
    {
        yyval.data.intVal = yyvsp[-2].data.intVal + yyvsp[0].data.intVal;
        yyval.data.type = _int;
    }
    else if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.intVal + yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _int)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal + yyvsp[0].data.intVal;
        yyval.data.type = _real;
    }
    else if (yyvsp[-2].data.type == _real && yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-2].data.realVal + yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }

;
    break;}
case 86:
#line 932 "parser.y"
{
    
    Trace("Reducing to arithmetic_expression\n");    
    if (yyvsp[-2].data.type == _int && yyvsp[0].data.type == _int)
    {
        yyval.data.intVal = yyvsp[-2].data.intVal % yyvsp[0].data.intVal;
        yyval.data.type = _int;
    }

;
    break;}
case 87:
#line 943 "parser.y"
{
    Trace("Reducing to arithmetic_expression\n");    
    ret_union* ret = lookup(yyvsp[0].idVal);
    if (!ret)
    {
        printf("[Error]: %s not declared\n", yyvsp[0].idVal);
        exit(1);
    }
    if (ret->type == _int)
    {
        yyval.data.intVal = ret->data.intVal;
        yyval.data.type = _int;
    }
    else if (ret->type == _real)
    {
        yyval.data.realVal = ret->data.realVal;
        yyval.data.type = _real;
    }
    // todo: check symbol table for id
;
    break;}
case 88:
#line 964 "parser.y"
{
    // Trace("Reducing to arithmetic_expression\n");    
    if (yyvsp[0].data.type == _int)
    {
        yyval.data.intVal = yyvsp[0].data.intVal;
        yyval.data.type = _int;
    }
    else if (yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }
;
    break;}
case 89:
#line 978 "parser.y"
{

    // Trace("Reducing to arithmetic_expression\n");    
    if (yyvsp[-1].data.type == _int)
    {
        yyval.data.intVal = yyvsp[-1].data.intVal;
        yyval.data.type = _int;
    }
    else if (yyvsp[-1].data.type == _real)
    {
        yyval.data.realVal = yyvsp[-1].data.realVal;
        yyval.data.type = _real;
    }
;
    break;}
case 90:
#line 993 "parser.y"
{
    
    // Trace("Reducing to arithmetic_expression\n");    
    if (yyvsp[0].data.type == _int)
    {
        yyval.data.intVal = -yyvsp[0].data.intVal;
        yyval.data.type = _int;
    }
    else if (yyvsp[0].data.type == _real)
    {
        yyval.data.realVal = -yyvsp[0].data.realVal;
        yyval.data.type = _real;
    }
;
    break;}
case 91:
#line 1017 "parser.y"
{
        Trace("Reducing to procedure_declaration\n");
;
    break;}
case 92:
#line 1023 "parser.y"
{
    Trace("Reducing to procedure start\n");

    currentScope = currentScope + usedScopeCount + 1;
    if(subLoopStartCount != 0)
    {
        currentScope = currentScope - usedScopeCount;
    }
    subLoopStartCount++;
    usedScopeCount++;


;
    break;}
case 93:
#line 1041 "parser.y"
{
    char* id = yyvsp[-6].idVal;
    unionData* unionPtr = (unionData*)malloc(sizeof(unionData));
    unionPtr->_const = 0;
    unionPtr->type = _procedure;
    insert_symbol(id, unionPtr);

    currentScope--;
    subLoopEndCount++;
    if(subLoopStartCount == subLoopEndCount)
    {
        currentScope = currentScope - usedScopeCount + subLoopEndCount;
        subLoopEndCount = 0;
        subLoopStartCount = 0;
    }
    printf("currentScope: %d, usedScopeCount: %d, subLoopEndCount: %d, subLoopStartCount: %d\n", currentScope, usedScopeCount, subLoopEndCount, subLoopStartCount);
;
    break;}
case 94:
#line 1067 "parser.y"
{
    Trace("Reducing to function_declaration\n");
;
    break;}
case 95:
#line 1073 "parser.y"
{
    Trace("Reducing to function start\n");

    currentScope = currentScope + usedScopeCount + 1;
    if(subLoopStartCount != 0)
    {
        currentScope = currentScope - usedScopeCount;
    }
    subLoopStartCount++;
    usedScopeCount++;


;
    break;}
case 96:
#line 1091 "parser.y"
{
    char* id = yyvsp[-8].idVal;
    unionData* unionPtr = (unionData*)malloc(sizeof(unionData));
    unionPtr->_const = 0;
    unionPtr->type = _function;
    insert_symbol(id, unionPtr);

    currentScope--;
    subLoopEndCount++;
    if(subLoopStartCount == subLoopEndCount)
    {
        currentScope = currentScope - usedScopeCount + subLoopEndCount;
        subLoopEndCount = 0;
        subLoopStartCount = 0;
    }
    printf("currentScope: %d, usedScopeCount: %d, subLoopEndCount: %d, subLoopStartCount: %d\n", currentScope, usedScopeCount, subLoopEndCount, subLoopStartCount);
;
    break;}
case 98:
#line 1116 "parser.y"
{
    
    char* id = yyvsp[-2].idVal;
    unionData* unionPtr = (unionData*)malloc(sizeof(unionData));
    unionPtr->_const = 0;
    unionPtr->type = yyvsp[0].type;
    insert_symbol(id, unionPtr);
;
    break;}
case 99:
#line 1125 "parser.y"
{
;
    break;}
case 100:
#line 1131 "parser.y"
{
    char* id = yyvsp[-2].idVal;
    unionData* unionPtr = (unionData*)malloc(sizeof(unionData));
    unionPtr->_const = 0;
    unionPtr->type = yyvsp[0].type;
    insert_symbol(id, unionPtr);
    // Trace("Reducing to more args declare\n");
;
    break;}
case 101:
#line 1141 "parser.y"
{
;
    break;}
case 102:
#line 1149 "parser.y"
{ 
    char* id = yyvsp[-2].idVal;
    unionData* unionPtr = (unionData*)&yyvsp[0].data;
    unionPtr->_const = 1;
    insert_symbol(id, unionPtr);
;
    break;}
case 103:
#line 1156 "parser.y"
{
    char* id = yyvsp[-4].idVal;
    unionData* unionPtr = (unionData*)&yyvsp[0].data;
    unionPtr->_const = 1;
    if(yyvsp[-2].type != yyvsp[0].data.type)
    {
        printf("---------------[Warning]: type mismatch\n");
    }
    unionPtr->type = yyvsp[-2].type;
    insert_symbol(id, unionPtr);
;
    break;}
case 104:
#line 1168 "parser.y"
{
    char* id = yyvsp[-2].idVal;

    unionData* unionPtr = (unionData*)malloc(sizeof(unionData));
    unionPtr->_const = 0;
    unionPtr->type = yyvsp[0].type;

    insert_symbol(id, unionPtr);
;
    break;}
case 105:
#line 1178 "parser.y"
{
    char* id = yyvsp[-4].idVal;
    unionData* unionPtr = (unionData*)&yyvsp[0].data;
    unionPtr->_const = 0;
    if(yyvsp[-2].type != yyvsp[0].data.type)
    {
        printf("---------------[Warning]: type mismatch\n");
    }
    unionPtr->type = yyvsp[-2].type;
    insert_symbol(id, unionPtr);
;
    break;}
case 106:
#line 1190 "parser.y"
{
    char* id = yyvsp[-2].idVal;
    unionData* unionPtr = (unionData*)&yyvsp[0].data;
    unionPtr->_const = 0;
    insert_symbol(id, unionPtr);
;
    break;}
case 107:
#line 1198 "parser.y"
{
    char* id = yyvsp[-8].idVal;
    unionData* unionPtr = (unionData*)malloc(sizeof(unionData));
    unionPtr->_const = 0;
    unionPtr->arrSize = yyvsp[-2].intVal - yyvsp[-5].intVal + 2;
    // allocate memory for array
    switch (yyvsp[0].type)
    {
    case _int:
        unionPtr->type = _int_array;
        unionPtr->array.intArray = (int*)malloc(sizeof(int) * unionPtr->arrSize);
        for (int i = 0; i <= yyvsp[-2].intVal - yyvsp[-5].intVal + 1; i++)
        {
            unionPtr->array.intArray[i] = 0;
        }
        break;
    case _real:
        unionPtr->type = _real_array;
        unionPtr->array.realArray = (float*)malloc(sizeof(float) * unionPtr->arrSize);
        for (int i = 0; i <= yyvsp[-2].intVal - yyvsp[-5].intVal + 1; i++)
        {
            unionPtr->array.realArray[i] = 0;
        }
        break;
    case _bool:
        unionPtr->type = _bool_array;
        unionPtr->array.intArray = (int*)malloc(sizeof(int) * unionPtr->arrSize);
        for (int i = 0; i <= yyvsp[-2].intVal - yyvsp[-5].intVal + 1; i++)
        {
            unionPtr->array.intArray[i] = 0;
        }
        break;
    }
    insert_symbol(id, unionPtr);
;
    break;}
case 108:
#line 1238 "parser.y"
{
    yyval.type = _str;
;
    break;}
case 109:
#line 1242 "parser.y"
{
    yyval.type = _bool;
;
    break;}
case 110:
#line 1246 "parser.y"
{
    yyval.type = _char;
;
    break;}
case 111:
#line 1250 "parser.y"
{
    yyval.type = _real;
;
    break;}
case 112:
#line 1254 "parser.y"
{
    yyval.type = _int;
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 1258 "parser.y"




void yyerror(const char *msg)
{
    printf("!!!!!!!!!!!!!!!!!!!!!!!!![Error]: %s\n", msg);
}

int main(int argc, char *argv[])
{

        head = create_symbol_entry();
        /* open the source program file */
        yyparse();
        dump_symbol();
	    return 0 ;
        exit(0);

}



int yywrap(void)
{
    return 1;
}


